export const SET_FILTERED_TICKETS = 'SET_FILTERED_TICKETS';
export const CHANGE_SORT = 'CHANGE_SORT';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';
export const SET_LOADING = 'SET_LOADING';
